### ISSUE TITLE
Buttons of popup unreadable

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#480] opened 2021-05-20 06:27 UTC
How to reproduce:
Select a  POI "Nette Toilette".

Current behavior:
Buttons are not readable, font sizes of heading and content are inapprobiate:
<img width="288" alt="grafik" src="https://user-images.githubusercontent.com/2187389/118929631-0d2f0780-b945-11eb-8477-7f7b4676fd6f.png">

Expected behavior:
Buttons are readable (if Mangel melden takes to much place, we should display it only for address popups, as is currently the case fror dt-1). Details text font size should not be larger than heading.

**Comment by andreashelms** [comment] 2021-05-20 14:03
Duplicate of #469

@Denis306 Can be closed?

**Comment by Denis306** [comment] 2021-05-20 14:11
I think this one is more regarding the buttons and not the content of the pop up. I talked with @leonardehrenfried about this yesterday. Since we added the "Mangel melden" Button in the middle the others get squeezed out. Maybe we need to make the popups a bit bigger.

**Comment by jpidelatorre** [comment] 2021-05-20 14:45
@andreashelms  BTW, I added the Report defect (Mangel Melden) button and fixed the problem with the width of the popup in #457 . I'm not sure if this is a regression or if I missed the type of popup. The way I solved this is in PR #459 (app/component/map/tile-layer/TileLayerContainer.js:430). Hope that helps.

**Comment by leonardehrenfried** [comment] 2021-05-20 15:18
Yes, simply make the popup wider.

**Comment by andreashelms** [comment] 2021-05-20 15:32
> @andreashelms BTW, I added the Report defect (Mangel Melden) button and fixed the problem with the width of the popup in #457 . I'm not sure if this is a regression or if I missed the type of popup. The way I solved this is in PR #459 (app/component/map/tile-layer/TileLayerContainer.js:430). Hope that helps.

Somehow your changes have no effect on the popups build on geojson layers. They had a fixed width, I now changed it to min-width with #488.

**Comment by MartinH-open** [comment] 2021-05-20 20:14
Hi - any chance to change the UI implementation in general?
Instead of squeezing the "Report defect (Mangel Melden)" button in the middle of two routing buttons - better add a separate button row above with just this button if function is available for the POI.

**Comment by samia-roubaa** [comment] 2021-05-29 11:40
QA validation; Button only exists for addresses

**Closed** 2021-05-31 07:17 UTC
Labels: bug
