### ISSUE TITLE
Add realtime icon to departure and arrival time

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#192] opened 2020-05-14 05:46 UTC
At the moment only the intermediate stops of an itinerary show the green realtime icon and colour.

![image](https://user-images.githubusercontent.com/151346/81897373-c7639480-95b6-11ea-9905-1e72b278d350.png)

Please also add the same style to the departure and arrival time.

**Comment by Beck-berry** [comment] 2020-05-19 07:05
By departure and arrival you mean the very first and the very last time of the route or every departure and arrival time of each leg? (So on the picture below: 9:05 and 9:21 or all of the times?)

We already managed to add the real time "sign" to the departure time of transit legs.
![Screenshot_2020-05-19_09-01-56](https://user-images.githubusercontent.com/46535522/82295050-691c2480-99af-11ea-8a82-b9c7318051ab.png)

**Comment by hbruch** [comment] 2020-05-19 07:11
That already looks great. There is really no logic yet to support this?
If realtime time is different from original, we should not show it in green color but e.g. in orange. Do you think there is a way to display in such cases the original departure time as well, so the user knows the difference?

**Comment by Beck-berry** [comment] 2020-05-19 07:50
There is a boolean variable `realTime` in each leg object and if it's true, the real time sign is rendered.
There is also a `startTime` variable which is the timetable departure, but how could we compare the real time departure and the timetable departure if `realTime` is only a boolean?

**Comment by leonardehrenfried** [comment] 2020-05-28 07:57
The GraphQL schema knows the field `arrivalDelay`: https://github.com/mfdz/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java#L1638-L1643

@Beck-berry can you add this to the Graphql query and see if you can get any useful information?

**Comment by Beck-berry** [comment] 2020-05-28 10:15
There were a variable `departureDelay` which was `undefined` until this point. Now I added it (and `arrivalDelay` too) to the GraphQL query, and has a value, so thanks!

@hbruch  There is a `delayThreshold` which can be set in the config, it is 180 sec by default. Is it ok for us to use or would you prefer another interval?

**Comment by Beck-berry** [comment] 2020-05-28 11:09
![Screenshot_2020-05-28_12-36-15](https://user-images.githubusercontent.com/46535522/83134216-51961780-a0e4-11ea-822e-8156b86ac177.png)
- [x] less space between the times
- [ ] the orange color should be a bit more reddish
- [ ] the stop should be orange as well (`arrivalDelay`)
- [ ] display delay in "near you" view (somehow)

**Comment by leonardehrenfried** [comment] 2020-06-02 10:02
Do we have an idea how to display it in the departure board?

**Comment by leonardehrenfried** [comment] 2020-06-02 10:16
Holger is on holiday this week. Did we agree that we will merge it without the departure board?

**Comment by Beck-berry** [comment] 2020-06-03 10:22
About the StopPage:
![Screenshot_2020-06-03_12-17-49](https://user-images.githubusercontent.com/46535522/83625518-50596480-a594-11ea-9959-2a4c5ca26bf5.png)
Have you noticed that some departure times are duplicated?
Also the first 12:30 is the original departure time and the next one, 12:33 is already fixed by the departureDelay. (Or can it be a super weird accident that the delay is 192 secs and the difference between the two epoch times is also 192?)

**Comment by leonardehrenfried** [comment] 2020-06-03 10:26
Can you send a link? I have the feeling that the source data is at fault here.

**Comment by Beck-berry** [comment] 2020-06-03 10:27
https://mih.mitfahren-bw.de/haltestellen/hbg%3Ade%3A08115%3A4513%3A0%3A3?locale=en

**Comment by Beck-berry** [comment] 2020-06-03 10:39
StopPage looks like this if there is a delay:
![Screenshot_2020-06-03_12-37-46](https://user-images.githubusercontent.com/46535522/83627342-0cb42a00-a597-11ea-930d-7512093fc3bb.png)
Line-through should be added if you like it this way. (The same class cannot be applied, have to find a workaround.)

**Comment by leonardehrenfried** [comment] 2020-06-03 10:41
Is it possible to move it to the right of the scheduled time?

**Comment by leonardehrenfried** [comment] 2020-06-03 10:44
Btw, there is indeed an error in the source data:

https://mih.mitfahren-bw.de/routen/hbg:2-774-s20-1/haltestellen/hbg:2-774-s20-1:0:01?sort=no
https://mih.mitfahren-bw.de/routen/hbg:31-774-j20-1/haltestellen/hbg:31-774-j20-1:0:02?sort=no

Holger has a way to report this to the transport company.

**Comment by Beck-berry** [comment] 2020-06-03 10:48
There _is_ a way:
![Screenshot_2020-06-03_12-46-25](https://user-images.githubusercontent.com/46535522/83628102-45083800-a598-11ea-8379-e6ee7ad7bea5.png)
It is kind of okay here (of course would need some css) but on mobile devices it won't have enough space:
![Screenshot_2020-06-03_12-48-21](https://user-images.githubusercontent.com/46535522/83628284-8567b600-a598-11ea-893e-74b479af9330.png)

**Comment by leonardehrenfried** [comment] 2020-06-03 10:54
![signal-attachment-2020-06-03-125314](https://user-images.githubusercontent.com/151346/83628737-44bc6c80-a599-11ea-8921-3e5f7a621d3f.png)

I mean there is room if we make the Leaves column wider, isn't it?

**Comment by Beck-berry** [comment] 2020-06-03 10:57
Yes, we can do that.

**Comment by hbruch** [comment] 2020-06-03 18:09
Concerning duplicated bus trips: For new issues, please open a new ticket so we discuss a single issue per ticket. The issue is already communicated to the transit agency and they will fix it with their next software release (got no info when this will be). Please open nevertheless an explicit issue for this, as we have multiple root causes. Another one (usually for trains only) is https://github.com/mfdz/GTFS-Issues/issues/51: for split/merged trains, drop-off/pickup type are not correctly set. And finally, duplicates might be created erroneously by opt when applying trip updates. We shall examine this when the GTFS data at least is fixed.

**Comment by Beck-berry** [comment] 2020-06-04 07:29
StopPage:
on desktop:
![Screenshot_2020-06-04_09-21-20](https://user-images.githubusercontent.com/46535522/83727544-86a2ec80-a645-11ea-94b8-31dd59436cab.png)
on mobile:
![Screenshot_2020-06-04_09-20-08](https://user-images.githubusercontent.com/46535522/83727555-8c003700-a645-11ea-8229-f398a5310a24.png)

I made the time column wider so it looks ok. Let me know what you think.

**Comment by leonardehrenfried** [comment] 2020-06-04 07:37
I think the "4 min" display is misleading in this case. People could interpret it as "4 minutes late". Can we have the actual time?

**Comment by Beck-berry** [comment] 2020-06-04 07:41
Of course:
![Screenshot_2020-06-04_09-41-33](https://user-images.githubusercontent.com/46535522/83729205-9de2d980-a647-11ea-8158-da1840c08086.png)

**Comment by leonardehrenfried** [comment] 2020-06-04 07:46
I like it. Can we have the scheduled time first, just like in the itinerary overview?

**Comment by Beck-berry** [comment] 2020-06-04 07:48
Sure thing:
![Screenshot_2020-06-04_09-47-46](https://user-images.githubusercontent.com/46535522/83729827-79d3c800-a648-11ea-87d4-fd197b49ed96.png)

**Comment by leonardehrenfried** [comment] 2020-06-04 07:54
Looks great.

On to the popup!

**Comment by Beck-berry** [comment] 2020-06-04 08:39
Btw, should we also display the delay on the front page, at the "near you" view?

**Comment by leonardehrenfried** [comment] 2020-06-04 08:40
Yes, I forgot about that one.

**Comment by Beck-berry** [comment] 2020-06-04 08:41
About the popup: looks like it uses the same components as the stop page...
![Screenshot_2020-06-04_10-40-15](https://user-images.githubusercontent.com/46535522/83734866-dab2ce80-a64f-11ea-9fcc-c07c2d42b53d.png)

**Comment by Beck-berry** [comment] 2020-06-04 08:48
This looks strange even if the times under each other.
![Screenshot_2020-06-04_10-47-39](https://user-images.githubusercontent.com/46535522/83735592-db983000-a650-11ea-85fe-4c0af824eb72.png)

**Comment by leonardehrenfried** [comment] 2020-06-04 08:49
Yes, that's confusing. What if you make the first column wider and the second one narrower?

**Comment by Beck-berry** [comment] 2020-06-04 08:55
Something like this?
![Screenshot_2020-06-04_10-55-16](https://user-images.githubusercontent.com/46535522/83736432-e99a8080-a651-11ea-9801-049b07b5dd8b.png)

**Comment by leonardehrenfried** [comment] 2020-06-04 08:56
Yes, it will look a little weird if there is no delay but i like it better.

Or can we make the width flexible?

**Comment by Beck-berry** [comment] 2020-06-04 09:30
Ok, I made the width flexible, so as if there is delay, the time column will be wider, otherwise the original width remains.
![Screenshot_2020-06-04_11-30-09](https://user-images.githubusercontent.com/46535522/83740172-c6260480-a656-11ea-9251-30af6e85ca1c.png)

**Comment by Beck-berry** [comment] 2020-06-05 07:43
"Near you" would definitely look overcrowded with the original time info:
![Screenshot_2020-06-05_09-40-29](https://user-images.githubusercontent.com/46535522/83850323-0ea1f880-a711-11ea-8b3f-2bdd4c6d194f.png)

**Closed** 2020-06-09 07:50 UTC
