### ISSUE TITLE
User Feedback: question/error about Bike routes

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#528] opened 2021-05-31 10:25 UTC
From: Reinhold Schick Platz  
To: Gäufelden
By BIKE

 (L1184) Current behavior: displayed are main streets 

Expected from the user is that the bike roads are shown instead of the main roads
![b_5dd35c13-933f-48d3-b924-2c7b8eca839a_1622398347](https://user-images.githubusercontent.com/84389152/120178930-4baca800-c20a-11eb-9812-0eba1e545358.png)

**Comment by hbruch** [comment] 2021-05-31 10:28
This is a duplicate of #525 and is already fixed, not yet deployed. Closing here

**Closed as completed by hbruch** 2021-05-31 10:28 UTC
Labels: bug
