### ISSUE TITLE
Changing the language while in the tab "timetable" shows an exception

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#620] opened 2021-06-13 14:56 UTC
Scenario:
- Open the details of a train station
- Go the tab "timetable"
- Choose the current language
- The app returns the exception "Internal Server Error"
![image](https://user-images.githubusercontent.com/83356918/121812486-2dae6100-cc68-11eb-9510-73265c739606.png)

Beta version:
 image: mfdz/opentripplanner:otp2-a0c0ea9082ac93f3b3e62bdb23c9c8da1622e632
 image: stadtnavi/digitransit-ui:f62cb548ded409d7c02fd0744fc798ffbdfc8a8d
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:6af73d1f1b27aa379596b4b270a24514eed6d95d
Last version change: 2021-06-12T07:47:43+0200

**Comment by jpidelatorre** [comment] 2021-06-17 05:57
Apparently, this is not happening anymore. Something changed that solved the problem recently. I tested in multiple environments (dev, qa, beta, local) and the problem doesn't appear in any of them. Here's the URL used int the body of the issue.

> https://herrenberg.beta.stadtnavi.eu/haltestellen/hbg%3Ade%3A08115%3A4512%3A1%3A3/fahrplan

However, there's a way of triggering the error by accessing a URL that points to a non-existing train station:

> https://herrenberg.beta.stadtnavi.eu/haltestellen/hbg%3Ade%3A08115%3A4512%3A0%3A3/fahrplan

The difference between both URLs is the pattern Id. Here's the difference:

> hbg : de : 08115 : 4512 : 1 : 3
> hbg : de : 08115 : 4512 : 0 : 3

I suppose this can cause the problem to appear when multiple stations occupy the same space. Maybe @leonardehrenfried can add something to this.

**Comment by Denis306** [comment] 2021-06-18 08:29
@samia-roubaa could you re-test this? I am trying to reproduce the issue but can't anymore on beta.

**Comment by leonardehrenfried** [comment] 2021-06-18 09:16
I have a repro case which is probably the same issue:

1. visit https://herrenberg.beta.stadtnavi.eu/geojson?lat=48.5893128&lng=8.8648539&language=en&name=Radsport+Holczer&content=Opening+hours%3A+Mo-Tu%2CFr+09%3A00-18%3A30%3B+Th+09%3A00-20%3A00%3B+Sa+09%3A00-14%3A00%2C+Wheelchair%3A+yes
2. Change language

**Comment by leonardehrenfried** [comment] 2021-06-18 09:17
In fact it seems that just visiting the geojson URL breaks the app.

**Comment by Denis306** [comment] 2021-06-18 09:24
Okay, I would probably create a new issue for that? What do you think @leonardehrenfried ?

**Comment by jpidelatorre** [comment] 2021-06-18 09:25
The server shouldn't respond with a 500 error.

**Comment by leonardehrenfried** [comment] 2021-06-18 09:25
> Okay, I would probably create a new issue for that? What do you think @leonardehrenfried ?

https://github.com/stadtnavi/digitransit-ui/issues/649

**Comment by leonardehrenfried** [comment] 2021-06-18 09:26
> The server shouldn't respond with a 500 error.

The server in this case is the server-side rendering of the react app. When you run it locally you see the stacktrace.

**Comment by leonardehrenfried** [comment] 2021-06-18 09:30
If I remember correct it tries to access `window` which doesn't exist in nodejs.

**Comment by Denis306** [comment] 2021-06-21 16:43
@leonardehrenfried I am closing this as #649 was also closed and the issue is fixed.

**Closed as completed by Denis306** 2021-06-21 16:43 UTC
Labels: next, bug
