### ISSUE TITLE
Webapp keeps loading in certain case very long

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#559] opened 2021-06-02 13:00 UTC
https://herrenberg.beta.stadtnavi.eu/reiseplan/Herrenberg%20Benzstra%C3%9Fe%2C%20Seestra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.599033073809274%2C8.871459960937502/Seelesplatz%3A%3A48.59741400223771%2C8.86926993727684?arriveBy=true&time=1622630738

At first the route is shown
Open settings and enable all Sharing and Carpool options
--> the system keeps loading and nothing happens
also the Settings button does not open to reset my settings

![grafik](https://user-images.githubusercontent.com/84389152/120484279-33c45800-c3b3-11eb-93d6-68b3e48a1414.png)

If the reason is that this is a very short route then a message should be shown to indicate this.

**Comment by samia-roubaa** [comment] 2021-06-02 13:50
duplicate of #554.

**Closed as completed by samia-roubaa** 2021-06-02 13:50 UTC
Labels: bug
