### ISSUE TITLE
P&R not working for this route

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#681] opened 2021-06-22 10:54 UTC
https://herrenberg.beta.stadtnavi.eu/reiseplan/Bahnhof%20Herrenberg%2C%2071083%20Herrenberg%3A%3A48.5943214%2C8.8621132/Vorsteigstra%C3%9Fe%2C%2070193%20Stuttgart%3A%3A48.7812373%2C9.1553375?time=1624360500

Park & Ride mode doesn't show any car routes on the webapp.

**Reproduce:**
1. Click on the url
2. Click on P&R tile
3. Nothing will happen

**Additional context:**
On the mobile app it returns routes for P&R.[IOS v1.2.9]
_Screenshots for mobile:_
![IMG-9622](https://user-images.githubusercontent.com/84456072/122912542-b9a34580-d358-11eb-9cbd-2789d5e8c6ec.PNG)![IMG-9621](https://user-images.githubusercontent.com/84456072/122912482-adb78380-d358-11eb-8eff-a91706d686fb.PNG)

**Comment by ahmed-nawar** [comment] 2021-06-28 10:14
Related to https://github.com/stadtnavi/digitransit-ui/issues/693#issuecomment-869537178

**Comment by leonardehrenfried** [comment] 2021-07-13 09:51
Duplicate of #693

**Closed as completed by leonardehrenfried** 2021-07-13 09:51 UTC
Labels: next, bug
