### ISSUE TITLE
Count of available rental bikes in the details differs from the count shown in a routing suggestion

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#557] opened 2021-06-02 12:10 UTC
Scenario:
1. Go to herrenberg.beta.stadtnavi.eu
2. Plan a trip from Nufringen to Kuppingen (bus disabled in settings and bike rental is enabled)
3. The route suggested shows that the available rental bikes is 10
![image](https://user-images.githubusercontent.com/83356918/120477365-fa3c1e80-c3ab-11eb-8feb-9a6e32a08247.png)
4. Remove all the search critiera and open the details of the bike rental station "Bhf. Herrenberg / Kalkofenstraße" (bike rental station that appeared in the route suggestion)
5. The details will show that the available bikes for rental are 9 and not 10
![image](https://user-images.githubusercontent.com/83356918/120477630-4b4c1280-c3ac-11eb-8f91-e7dd20dc0c10.png)

Beta version:
 image: mfdz/opentripplanner:otp2-3621b1e591409b23d96b6253472d6f4bac88057e
 image: stadtnavi/digitransit-ui:55cf55e3c01e08fef8f023c54415969998197dc9
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b83aaea7eab1ed8eaa9154ce3ce63aca9c949afd
Last version change: 2021-06-02T13:32:55+0200

**Comment by Denis306** [comment] 2021-06-04 22:00
@samia-roubaa Apparently this issue is not reproducable anymore. Could you please check again and close this issue then?

I just checked the route you provided and it says 7 bikes are available.
![image](https://user-images.githubusercontent.com/63004289/120866683-c2420080-c590-11eb-8a9a-028a79057c9b.png)

And if i delete everything and check the bike rental station it also says 7.
![image](https://user-images.githubusercontent.com/63004289/120866732-cf5eef80-c590-11eb-8880-ef31191fce72.png)

**Comment by Denis306** [comment] 2021-06-07 06:47
Apparently now the bug is happening again.

**Comment by jpidelatorre** [comment] 2021-06-09 06:01
After tracking down the source of the problem, I can say with confidence that this problem is not caused by the front-end. Both quantities come from two GraphQL queries and remain unaltered through the application.

For this one:
![image](https://user-images.githubusercontent.com/104569/121299210-1156a100-c8c3-11eb-877f-e1444a505f75.png)

This is the query:

https://github.com/stadtnavi/digitransit-ui/blob/c51e7cec7dd3c6bffa8741e824fc64fac5d361cf/app/routes.js#L205-L211

And for this one:
![image](https://user-images.githubusercontent.com/104569/121299444-6f838400-c8c3-11eb-89ea-4b63e7edef3e.png)

I believe this is the query:
https://github.com/stadtnavi/digitransit-ui/blob/c51e7cec7dd3c6bffa8741e824fc64fac5d361cf/app/component/SummaryPage.js#L670-L730

@leonardehrenfried What should we do in this case?

**Comment by andreashelms** [comment] 2021-06-09 06:17
@jpidelatorre I don't think this query can be the cause of that issue, because I added that query only two days ago with https://github.com/stadtnavi/digitransit-ui/pull/580. And most of the time it isn't executed, only for requests with departure time between 21pm and 5am.

**Comment by leonardehrenfried** [comment] 2021-06-09 06:54
It is possible that in between querying and for the route and then looking at the bike station a little later someone just rented a bike and hence the count is lower. My feeling is that this was the case here.

Since it is not possible to reproduce anymore(?), I'd suggest to close this.

**Comment by jpidelatorre** [comment] 2021-06-09 07:31
> It is possible that in between querying and for the route and then looking at the bike station a little later someone just rented a bike and hence the count is lower. My feeling is that this was the case here.

This would also explain why the problem appears sometimes and sometimes don't.

**Comment by jpidelatorre** [comment] 2021-06-09 07:33
@andreashelms I could be wrong about the queries. The problem really is that the data goes down to the components without being altered.

**Closed as completed** 2021-06-10 09:46 UTC
Labels: bug
