### ISSUE TITLE
Transportation mode "Ruftaxi" does not show any results on the map

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#618] opened 2021-06-13 14:49 UTC
Scenario:
- Origin: Schuhhaus Breitner e.K., Bronngasse 19, 71083 Herrenberg
- Destination: Sommerrain 9, 71083 Herrenberg
- Departure: 22:08
The app returned the following transportation modes
![taxi option does not show any results](https://user-images.githubusercontent.com/83356918/121812180-35213a80-cc67-11eb-9be1-906b6e5376d3.png)

When I click on the transportation mode "Taxi", the map does not change and the relevant route is not shown.

 image: mfdz/opentripplanner:otp2-a0c0ea9082ac93f3b3e62bdb23c9c8da1622e632
 image: stadtnavi/digitransit-ui:f62cb548ded409d7c02fd0744fc798ffbdfc8a8d
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:6af73d1f1b27aa379596b4b270a24514eed6d95d
Last version change: 2021-06-12T07:47:43+0200

**Comment by ahmed-nawar** [comment] 2021-06-23 13:42
Cannot reproduce. I think it is fixed.

**Comment by ahmed-nawar** [comment] 2021-06-27 13:20
This is fixed on the beta version.
The dev is broken.(see screenshot)
https://dev.stadtnavi.eu/reiseplan/Schuhhaus%20Breitner%20e.K.%2C%20Bronngasse%2019%2C%2071083%20Herrenberg%3A%3A48.5955157%2C8.86795/Sommerrain%209%2C%2071083%20Herrenberg%3A%3A48.5911992%2C8.859850849999999?time=1624829400
**_Suggestions for route_**
![image](https://user-images.githubusercontent.com/84456072/123545968-1046c000-d75b-11eb-937d-276e7424db15.png)

**_After clicking on the RT icon_**
![image](https://user-images.githubusercontent.com/84456072/123545981-218fcc80-d75b-11eb-8074-73c67483e20e.png)

**Comment by andreashelms** [comment] 2021-06-28 15:24
Now works on dev, too. Can't reproduce anymore.

**Closed as completed** 2021-06-28 15:58 UTC
Labels: bug

**Comment by ahmed-nawar** [comment] 2021-06-28 16:55
I confirm that I cannot reproduce on dev. But there is a warning message which I think is unnecessary.
```
No route suggestions were found with the your settings. However, we found the following route options:
```
