### ISSUE TITLE
Missing details when viewing the details of a bicycle parking, Ladestationen and Nette Toiletten

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#429] opened 2021-05-10 20:10 UTC
Scenario:
- Choose the POI "Fahrrad-Abstellanlagen"
- Open the details of any parking place
The following appears:
- A general title
- missing info for the Tarifzone
- the text "Stellplätze x" is not aligned
![image](https://user-images.githubusercontent.com/83356918/117718464-63c97280-b1dc-11eb-878f-042ee5bbbf35.png)
![image](https://user-images.githubusercontent.com/83356918/117718490-6d52da80-b1dc-11eb-8595-4788c2f24409.png)

Scenario:
- Choose the POI "Ladestationen"
- Open the details of any Ladestation
The following appears:
- missing info for the Tarifzone
- the text "Stellplätze x" is not aligned
![image](https://user-images.githubusercontent.com/83356918/117720682-3fbb6080-b1df-11eb-8c7e-70ff81a941ac.png)
![image](https://user-images.githubusercontent.com/83356918/117720702-46e26e80-b1df-11eb-843a-d4ea254c4bf2.png)

Scenario:
- Choose the POI "Nette Toilette"
- Open the details of any Nette Toilette
The following appears:
- missing info for the Tarifzone
- the text "Wickelmöglichkeit" and "Öffnungszeiten" is not aligned
![image](https://user-images.githubusercontent.com/83356918/117721592-57dfaf80-b1e0-11eb-92f7-b909a7d7ea1e.png)

QA version:
 image: mfdz/opentripplanner:otp2-3bcf0f41606d3b70f681b2f355064f71d3ace246
 image: stadtnavi/digitransit-ui:fa8193fbace646e9f94132cda0732a9d8435c802
 image: stadtnavi/hsl-map-server:a563129166683c99bfdedb88f00bb9117afff726
 image: stadtnavi/fares-service:a9d1987be58d86b877699ede204ad537afd0bda1

**Comment by MartinH-open** [comment] 2021-05-10 22:28
Question: Is the info about the "Tarifzone" anything useful at all for such POIs?

Instead of "Gebührenpflichtig: Nein" or "Gebührenpflichtig: Ja" I prefer
"Gebühren: keine" or "Gebühren: Ja" or even "Gebühren: 1€" or whatever ..

**Comment by samia-roubaa** [comment] 2021-05-19 06:54
Bug validation on QA system: partially failed

1. Fahrradparkplätze:
There is a parking place near Kalkofenstraße that does not show any information about the available parking slots
![image](https://user-images.githubusercontent.com/83356918/118768228-0b9b0c00-b87f-11eb-851b-ec7fc6187f6d.png)

2. Ladestationen:
The Elektroauto-Ladestation shows a weird message stating that "2 out 1 slots are free"
![image](https://user-images.githubusercontent.com/83356918/118768413-4309b880-b87f-11eb-8c65-d4f69b88c257.png)

3. All details of the mentioned POIs:
The font is too big and not unified with other POIs details' views
![image](https://user-images.githubusercontent.com/83356918/118768641-8b28db00-b87f-11eb-889b-ce06c7c27c91.png)
![image](https://user-images.githubusercontent.com/83356918/118768713-9e3bab00-b87f-11eb-9f77-6a9afd36db48.png)

QA system version:
 image: mfdz/opentripplanner:otp2-15fd09f6e08683d05cfe96e1400a33356d17afa9
 image: stadtnavi/digitransit-ui:b10a74a97df348e1962ffc454571053966332520
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b80f1ce50fff9b72be5e9f8b02e0b374c7c5c833
Last version change: 2021-05-18T17:38:58+0200

**Comment by leonardehrenfried** [comment] 2021-05-19 12:47
1. Sometimes we just don't know how many spaces are available.
2. This is a bug that I just fixed. Embarrassing.
3. Duplicate of #469

**Closed** 2021-05-31 07:16 UTC
Labels: fixed-on-dev
