### ISSUE TITLE
Intermodal Bike+ÖPNV routes with RegioRad do not end at a RegioRad station (web and app)

### ISSUE THREAD

**Issue by stadtnavimanager** [stadtnavi/digitransit-ui#862] opened 2024-12-18 17:07 UTC
**Description:**  

When **RegioRad** is enabled in the settings, intermodal **Bike+Public Transport (Bike+ÖPNV)** routes include suggestions that combine **Public Transport (ÖPNV)** and **bike-sharing (RegioRad)**.  

However, these routes incorrectly end at the **entered destination**, rather than at a designated **RegioRad station** where the bike must be returned. This can mislead users and create practical issues for completing the trip.

---

**Steps to reproduce:**  

1. Open Stadtnavi and enable **RegioRad** in the **Settings** menu.  
2. Search for an intermodal **Bike+ÖPNV** route.  
3. Observe the suggested routes that include RegioRad.  

---

**Observed behavior:**  

The suggested route with RegioRad ends at the user’s destination instead of a valid RegioRad return station.  

**Expected behavior:**  

Routes that include RegioRad should end at a **RegioRad station** near the destination, where the shared bike can be returned.

---

**Screenshots:**  

_Attach relevant screenshots demonstrating the issue._  

---

**Environment:**  

- **Browser/App Version:** [Add version here]  
- **Operating System:** [Add OS here, e.g., Android, iOS, Windows 10]  

---

**Additional information:**  

Correcting this issue will ensure that users are provided with realistic and actionable route suggestions, improving the reliability of intermodal routes involving bike-sharing services.

**Comment by hbruch** [comment] 2024-12-18 17:16
This seems to be a duplicate of #861. I suggest closing this issue

**Closed as completed** 2024-12-19 08:52 UTC
